input_path: "../outputs/dataset_yeo17thick_2024_03_21.pkl"

connectivity_measure_type: "correlation"  # multiple or 'none'. If 'none', the initial time series matrix will be returned
edge_threshold: 0.9  # 90% correlation and above is considered