input_path: "/home/ubuntu/Dizertatie/fmri_analysis/MRI_Pain"
output_path: "/home/ubuntu/Dizertatie/fmri_analysis/MRI_Pain/derivatives"

#flags:
#  - "low-mem"

fs-license-file: "/home/ubuntu/Dizertatie/fmri_analysis/license.txt"

participant_label:
  - "sub-01"

task-id:
  - "rest"