# Read arguments
derivatives_dir: "../data/ds000030/derivatives/preprocess"
subjects: "ALL"  # a list or 'ALL'. If 'ALL', all will be read.
task: 'rest'

# Clean arguments
clean_arguments:
  high_pass: 0.009
  low_pass: 0.08
  t_r: 2
  detrend: True
  standardize: True
  tr_drop: 4

  confounds:  # based on the classification made by fMRIPrep team (https://fmriprep.org/en/stable/outputs.html#confounds)
  #  - basic_confounds  # 9 parameters, 6 rigid-body + 3 global signals
  #  - derivatives_of_basic  # derivatives for the basic confounds
  #  - power_2_basic  # power two of the basic + derivatives
  #  - outlier_detection  # TODO: merita folosite.
  #  - cosine_basis
    - compcor

# Atlas arguments
atlas_type: yeo
atlas_args:
  type: "thin_17"

output_path: "../data/processed/data_02_11_2024_thin17/dataset_yeo17thin_2024_11_02_h_train.pkl"