# MODEL
model_name: normative
model_path: "outputs/normative/ckpts/07_09_thick_correlation/model-epoch=932.ckpt"
fc_hidden_size:
  - 68  # ~136 / 2; (17**2 - 17) / 2 = 136
  - 23  # ~68 / 3
  - 68
activation: "leaky_relu"
norm_layer: "none"
dropout_prob: 0.5
input_areas: 17


# DATASET
ds_paths:
  healthy: "/home/ubuntu/Dizertatie/fmri_analysis/data/processed/data_2024_07_09_thick17/dataset_yeo17thick_2024_07_09_h_test.pkl"
  schz: "/home/ubuntu/Dizertatie/fmri_analysis/data/processed/data_2024_07_09_thick17/dataset_yeo17thick_2024_07_09_schz_test.pkl"
  bipolar: "/home/ubuntu/Dizertatie/fmri_analysis/data/processed/data_2024_07_09_thick17/dataset_yeo17thick_2024_07_09_bipolar_test.pkl"
  adhd: "/home/ubuntu/Dizertatie/fmri_analysis/data/processed/data_2024_07_09_thick17/dataset_yeo17thick_2024_07_09_adhd_test.pkl"
  hpain: "/home/ubuntu/Dizertatie/fmri_analysis/data/processed/data_2024_11_11_thick17/dataset_yeo17thin_2024_11_11_hpain_test.pkl"
  pain: "/home/ubuntu/Dizertatie/fmri_analysis/data/processed/data_2024_11_11_thick17/dataset_yeo17thin_2024_11_11_pain_test.pkl"

dataset_name: "ucla"
connectivity_measure_type: "correlation"  # multiple or 'none'. If 'none', the initial time series matrix will be returned
edge_threshold: 0.9  # 90% correlation and above is considered  # TODO: nefolosit.
batch_size: 1

metric: "mae"
output_dir: "outputs/normative/test/version_pain/"