# MODEL
model_name: normative
fc_hidden_size:
  - 68  # ~136 / 2; (17**2 - 17) / 2 = 136
  - 23  # ~68 / 3
  - 68
activation: "leaky_relu"
norm_layer: "none"
dropout_prob: 0.5
input_areas: 17

# DATASETS
dataset_name: ucla
train_path: "/home/ubuntu/Dizertatie/fmri_analysis/data/processed/data_2024_12_29_thin7/dataset_yeo7thin_2024_12_29_h_train.pkl"
val_path: "/home/ubuntu/Dizertatie/fmri_analysis/data/processed/data_2024_12_29_thin7/dataset_yeo7thin_2024_12_29_h_test.pkl"
connectivity_measure_type: "kendall"  # multiple or 'none'. If 'none', the initial time series matrix will be returned
edge_threshold: 0.9  # 90% correlation and above is considered  # TODO: nefolosit.
batch_size: 4

# TRAINER
# fine_tune_path: "/home/ubuntu/Dizertatie/fmri_analysis/outputs/normative/ckpts/07_09_thin_kendall/model-epoch=966.ckpt"
lr: 5e-4
weight_decay: 1e-5
logger: tensorboard  # csv, tensorboard
experiment_name: "my_experiment"
max_epochs: 1000
ckpt_args:
  metric: "val_mse_loss"
  mode: "min"
#early_stopping:
#  metric: "val_mse_loss"
#  mode: "min"
#  min_delta: 1e-5
#  patience: 50